# Generated by Django 3.1.3 on 2020-12-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_listings_whatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='whatchlist',
        ),
        migrations.CreateModel(
            name='WhatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howAdded', models.CharField(max_length=64)),
                ('Auctions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listings')),
            ],
        ),
    ]
