# Generated by Django 3.1.3 on 2020-12-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201203_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatchlist',
            old_name='howAdded',
            new_name='whoadd',
        ),
    ]
